---
# tasks file for k3s
- name: Control node initial setup
  block:
    - name: Download and install k3s control plane node
      ansible.builtin.shell: sudo curl -sfL https://get.k3s.io | sh -

    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../../kubeconfig
        flat: yes
      when: "'bastion' in group_names"

    - name: Load token content
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: token
  run_once: true
  when: "'bastion' in group_names"

  # nodetoken is passed as fact to playbook

- name: Setup worker node
  block:
    - set_fact:
        k3s_agent_command:  K3S_URL=https://{{ control_plane_ip }}:6443 K3S_TOKEN={{ nodetoken | b64decode }} sh  bootstrap.sh
          
    - name: Download k3s bootstrap script
      ansible.builtin.shell: curl -sfL https://get.k3s.io >> bootstrap.sh 

    - name: Install k3s worker nodes
      ansible.builtin.shell: sudo {{ k3s_agent_command }}
      # args:
      #   executable: /bin/bash
  when: "'workers' in group_names"
